site_name: CLI for unasync
site_url: https://github.com/leynier/unasync-cli
repo_url: https://github.com/leynier/unasync-cli
edit_uri: "https://github.com/leynier/unasync-cli/edit/main/docs"

theme:
  name: material
  language: en
  features:
    - navigation.instant
  palette:
    primary: black
    accent: light blue

nav:
  - Home: index.md

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - toc:
      permalink: 🔗

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/leynier
      name: LinkedIn
    - icon: fontawesome/brands/github
      link: https://github.com/leynier
      name: GitHub
    - icon: fontawesome/solid/code
      link: https://profile.codersrank.io/user/leynier
      name: Codersrank
    - icon: fontawesome/brands/medium
      link: https://medium.com/@leynier
      name: Medium
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/leynier41
      name: Twitter
    - icon: fontawesome/brands/telegram
      link: https://t.me/leynier
      name: Telegram
    - icon: fontawesome/solid/paper-plane
      link: mailto:leynier41@gmail.com
      name: Email
